# -*- coding: utf-8 -*-
"""DichKyTu.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YZ6eBdb9eLvPIc3nEVfg8HnY7iL8HjW8
"""

import string

alphabet = list(string.ascii_uppercase)
last = len(alphabet) - 1

print('Nhap 1: Ma hoa | Nhap 2: Giai ma')
n = int(input())


def mahoa(s,k):
  res = ''
  for c in s:
     index = alphabet.index(c)
     tmp = index + k
     if(tmp > last):
       res = res + alphabet[tmp - last - 1]
     else:
        res = res + alphabet[tmp]
  print(res)


def giaima(s,k):
  res = ''
  for c in s:
     index = alphabet.index(c)
     tmp = index - k
     if(tmp < 0):
       res = res + alphabet[last+1+tmp]
     else:
        res = res + alphabet[tmp]
  print(res)


if(n==1):
     print("Nhap van ban can ma hoa:")
     s = raw_input()
     print("Nhap so ky tu can dich:")
     k = int(input())
     s = s.upper()
     mahoa(s,k)

elif n ==2 :
     print("Nhap van ban can giai ma")
     s2 = raw_input()
     print("Nhap so ky tu can dich:")
     k2 = int(input())
     s2 = s2.upper()
     giaima(s2,k2)