# -*- coding: utf-8 -*-
"""VigenereCipher.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pur99uPcd6At0EuDkNOCHm80ch3HO_6X
"""

def TaoKey(string, key):
  key = list(key)
  if len(string) == len(key):
    return(key)
  else:
    for i in range(len(string) -len(key)):
      key.append(key[i % len(key)])
  return("" . join(key))


def MaHoa(string, key):
  encrypt_text = []
  for i in range(len(string)):
    x = (ord(string[i]) + ord(key[i])) % 26
    x += ord('A')
    encrypt_text.append(chr(x))
  return("" . join(encrypt_text))


def GiaiMa(encrypt_text, key):
  orig_text = []
  for i in range(len(encrypt_text)):
    x = (ord(encrypt_text[i]) -ord(key[i]) + 26) % 26
    x += ord('A')
    orig_text.append(chr(x))
  return("" . join(orig_text))


string = raw_input("Nhap van ban can ma hoa: ")
keyword = raw_input("Nhap tu khoa: ")
key = TaoKey(string, keyword)
encrypt_text = MaHoa(string,key)
print("Van ban ma hoa:", encrypt_text)
print("Van ban giai ma:", GiaiMa(encrypt_text, key))